### ISSUE TITLE
Tidier UI for all models

### ISSUE THREAD

**Issue by tgerke** [stopsack/risks#10]
Let's think of a less "base-y" way to access the individual models than 

> Individual models can be accessed as `fit$all_models[[1]]` through `fit$all_models[[6]]`

The right solution may also help with the volume of output in `tidy(fit_all)`

**Comment by stopsack** [comment]
I am with you regarding the aesthetics here. A higher priority for me, but still not at the top of the list, would be to make the tidyverse dependencies optional for the risks package, i.e. `Suggests` instead of `Depends`
