### ISSUE TITLE
Write tests for caseduplicate.R

### ISSUE THREAD

**Issue by tgerke** [stopsack/risks#11]
I've linted this one and made an assumption about intended matrix-initialization behavior (e.g. changing `coef.table <- matrix(, 0L, 4L)` to `coef.table <- matrix(0L, 4L)` but some unit tests would really help debug and enlighten as to where these functions come into play.

**Comment by stopsack** [comment]
Tests are important! Here is where they live:
https://github.com/stopsack/risks/tree/master/tests/testthat
