### ISSUE TITLE
Fitting functions don't handle interactions

### ISSUE THREAD

**Issue by tgerke** [stopsack/risks#5]
Usually a call like this would provide estimates for the interaction, but `riskratio()` does something unexpected. Perhaps we want to throw an error this kind of call (or do we want to allow this syntax interaction estimates)?
```
> fit_rr <- riskratio(death ~ stage*receptor, data = breastcancer)
> fit_rr

Risk ratio model
Call:  stats::glm(formula = death ~ stage * receptor, family = binomial(link = "logit"), 
    data = breastcancer, start = "(no starting values)")

Coefficients:
  stageStage I   stageStage II  stageStage III  
        0.0000          0.9161          1.7996  
```

**Comment by stopsack** [comment]
I see how this behavior could be unexpected and should be documented explicitly. With *marginal* standardization, we should indeed only be getting marginal estimates for (levels of) the exposure only, even if the underlying logistic model was fit including interaction terms between exposure and covariates.
