### ISSUE TITLE
Does `approach = "all"` option need a progress bar?

### ISSUE THREAD

**Issue by tgerke** [stopsack/risks#9]
The example in `models.Rmd` runs fairly quickly, but have you encountered other applications where one or more of the methods is very slow? If so, it could be good for us to include a progress bar so that the user can know which method is taking the longest / possibly to avoid that method.

**Comment by stopsack** [comment]
Nice to have but perhaps not essential for now. We could perhaps just document that `approach = "margstd_boot"` is guaranteed to take a few seconds at least, and `"glm_cem"` often does too when convergence is an issue.

**Comment by stopsack** [comment]
(is actually documented as part of simulation study)
